compilent_mngmt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('account.urls')),
    path('', include('frontend.urls')),
    path('api/v1/core/', include('core.urls'))
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (EmployeeList, EmployeeRetrieveView, EmployeeUpdateView, compilent_registration, CompilentList, CompilentRetrieveView,
                    CompilentUpdateView, CompilentWorkflowUpdateView, GetSource)

urlpatterns = [
    path('employee/list/', EmployeeList.as_view(), name='employee_list'),
    path('employee/details/<id>/', EmployeeRetrieveView.as_view(), name='employee_details'),
    path('employee/details/<id>/update/', EmployeeUpdateView.as_view(), name='employee_update'),
    path('add-complaint/', compilent_registration, name='compilent_registration'),
    path('complaint/list/', CompilentList.as_view(), name='compilent_list'),
    path('complaint/details/<id>/', CompilentRetrieveView.as_view(), name='compilent_details'),
    path('complaint/details/<id>/update/', CompilentUpdateView.as_view(), name='compilent_update'),
    path('complaint/details/<id>/workflow/', CompilentWorkflowUpdateView.as_view(), name='compilent_update'),
    path('complaint/source/', GetSource.as_view(), name='api_order_get_source'),
]

frontend/urls.py
from django.urls import path
from .views import (Home, UserLoginView, AflDasboardView, ManageStaff, AddNewEmployee, AflManageMemberEdit, ManageComplaint,
                    AddNewComplaint, AflManageComplaintsEdit, ComplaintView, AflManageComplaintsWorkflow)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', UserLoginView.as_view(), name='login_url'),
    path('dashboard/', AflDasboardView.as_view(), name='dashboard'),
    path('manage-staff/', ManageStaff.as_view(), name='manage_staff'),
    path('add-new-employee/', AddNewEmployee.as_view(), name='add_employee'),
    path('manage-employee/edit/', AflManageMemberEdit.as_view(), name="manage_members-edit"),
    path('manage-complaint/', ManageComplaint.as_view(), name='manage_complaint'),
    path('add-new-complaint/', AddNewComplaint.as_view(), name='add_complaint'),
    path('manage-complaint/edit/', AflManageComplaintsEdit.as_view(), name="manage_complaint-edit"),
    path('complaints/view/', ComplaintView.as_view(), name="complaint_view"),
    path('manage-complaint/workflow/', AflManageComplaintsWorkflow.as_view(), name="manage_complaint-workflow"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.conf import settings

class UserLoginForm(forms.Form):
	email = forms.CharField(label=_('Email'),max_length=250,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Email'}))
	password = forms.CharField(label=_('Password'),max_length=250,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Password'}))
	def __init__(self, *args, **kwargs):
		self.request = None
		if 'request' in kwargs:
			self.request = kwargs.pop('request', None)
		kwargs.setdefault('label_suffix', '')
		super(UserLoginForm, self).__init__(*args, **kwargs)

class AflAbstractUserForm(forms.Form):
	first_name = forms.CharField(max_length=20,label=_('First Name'))
	last_name = forms.CharField(max_length=20, label=_('Last Name'))
	email = forms.CharField(max_length=50, label=_('Email'))
	phone_number = forms.CharField(max_length=10, label=_('Phone Number'))
	title = forms.CharField(max_length=120, label=_('Title'))

	def __init__(self, *args, **kwargs):
		# pp("AflAbstractUserForm---------------")
		# Get 'initial' argument if any	
		initial_arguments = kwargs.get('initial', None)
		if not hasattr(self,'request') or not self.request:
			if initial_arguments:
				self.request = initial_arguments.get('request',None)
			else:
				self.request = None

		super(AflAbstractUserForm, self).__init__(*args, **kwargs)
		self.fields['last_name'].label = _('Last Name')
		self.fields['email'].label = _('Email address')
		self.fields['phone_number'].label = _('Phone Number')
		self.fields['title'].label = _('Title')

class UserCreationForm(AflAbstractUserForm):
	"""A form for creating new users. Includes all the required
	fields, plus a repeated password."""
	password = forms.CharField(label=_('Password'), widget=forms.TextInput(attrs={'class':'form-control','placeholder':_('Password')}))
	confirmpswd = forms.CharField(label=_('Password confirmation'), widget=forms.TextInput(attrs={'class':'form-control','placeholder':_('Password')}))
 
class AddNewEmployeeForm(UserCreationForm):
	"""docstring for AddNewStaffForm"""

	def __init__(self, *args, **kwargs):
		super(AddNewEmployeeForm, self).__init__(*args, **kwargs)


		if 'password' in self.fields:
			self.fields['password'].widget.attrs.update({
				'autocomplete': 'off',
				'disabled':True          #for preventing autocomplete some browser where above line not working such as Chrome
			})
		if 'confirmpswd' in self.fields:
			self.fields['confirmpswd'].widget.attrs.update({
				'autocomplete': 'off',
				'disabled':True			#for preventing autocomplete some browser where above line not working such as Chrome
			})
		self.fields['password'].label = _("Password")
		self.fields['confirmpswd'].label = _("Password confirmation")

class UserProfileForm(AflAbstractUserForm):

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop('request', None)
		super().__init__(*args, **kwargs)

class AddNewCompliantForm(forms.Form):
	options = (
		('', _('Please select')),
	)
	title = forms.CharField(label=_("Title"), required=True)
	description = forms.CharField(label=_("Description"), required=True, widget=forms.Textarea(attrs={'rows': 4, 'cols': 25}))
	assignee = forms.ChoiceField(
        choices=[
            ('', _('Please select'))
        ],
        label=_("Assignee"),
        widget=forms.Select(attrs={
            'class': 'form-control',
            'data-placeholder': _('Choose assignee'),
            'data-url': f'{settings.SERVER_URL}/api/v1/assignee-autocomplete/'
        })
    	)

	def __init__(self, *args, **kwargs):
		self.request = None
		if 'request' in kwargs:
			self.request = kwargs.pop('request', None)
		super(AddNewCompliantForm, self).__init__(*args, **kwargs)
		instance = kwargs.get('instance',{})

class EditComplaintForm(forms.Form):
	options = (
		('', _('Please select')),
	)
	title = forms.CharField(label=_("Title"), required=True)
	description = forms.CharField(label=_("Description"), required=True, widget=forms.Textarea(attrs={'rows': 4, 'cols': 25}))
	assignee = forms.ChoiceField(
        choices=[
            ('', _('Please select'))
        ],
        label=_("Assignee"),
        widget=forms.Select(attrs={
            'class': 'form-control',
            'data-placeholder': _('Choose assignee'),
            'data-url': f'{settings.SERVER_URL}/api/v1/assignee-autocomplete/'
        })
    	)

	def __init__(self, *args, **kwargs):
		self.request = None
		if 'request' in kwargs:
			self.request = kwargs.pop('request', None)
		super(EditComplaintForm, self).__init__(*args, **kwargs)
		instance = kwargs.get('instance',{})

class WorkflowComplaintForm(forms.Form):
	STATUS_CHOICES=[
		('new','New'),
		('triaged','Triaged'),
		('in_progress','In progress'),
		('resolved','Resolved'),
		('closed','Closed')
	]
	status = forms.ChoiceField(choices=STATUS_CHOICES, label=_('Status'), widget=forms.Select(), required=True)
	status_remark = forms.CharField(label=_("Remark"), required=True, widget=forms.Textarea(attrs={'rows': 4, 'cols': 25}))

	def __init__(self, *args, **kwargs):
		self.request = None
		if 'request' in kwargs:
			self.request = kwargs.pop('request', None)
		super(WorkflowComplaintForm, self).__init__(*args, **kwargs)
		instance = kwargs.get('instance',{})

frontend/templates/frontend/user/add-new-staff.html
{% load static %}
{% load widget_tweaks %}
{% comment %} {% load afl_language %} {% endcomment %}
{% load i18n %}
{% load templatehelpers %}
{% block maintitle %} {{label}} {% endblock %}

{% block content %}

<div class="m-content">
  <div class="m-portlet m-portlet--mobile">
    <div class="row">
      <div class="col-lg-12">
        <div class="loader" id="loader" style="display:none"></div>
       {% if form %}
        <form method="{{form.method|default:'POST'}}" {% if form.id %} id="{{form.id}}"{% endif %} class="{{form.class}} m-form m-form--label-align-right" action="{{form.action|default:request.path}}"  {% if files %} enctype="multipart/form-data"{% endif %} autocomplete="new"  novalidate >
        	{% comment %} {% if form.is_multilingual %}
        	    {{form|afl_default_language_tag}}
        	{% endif %} {% endcomment %}
          {% csrf_token %}
          <div class="m-portlet__body">
            {% if form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                {{ error }}
                {% endfor %}
              </div>
            {% endif %}
            {% for field in form.visible_fields %}
            <div class="form-group m-form__group">
              {{ field.label_tag }}
              {% if form.is_bound %}
              {% if field.errors %}
              {% with field.field.widget.attrs.class|add:" form-control m-input is-invalid" as field_class %}
              {% if field.field.widget.attrs.field_suffix %}
              <div class="input-group">
                {% render_field field placeholder=field.label %}
                {% comment %} <div class="input-group-append">
                  {% afl_field_suffix form field %}
                </div> {% endcomment %}
              </div>
              {% elif field.field.widget.attrs.field_prefix %}
              <div class="input-group">
                {% comment %} <div class="input-group-prepend" style="width:100px;">
                  {% afl_field_prefix form field %}
                </div> {% endcomment %}
                {% render_field field class=field_class %}
            
              </div>
              {% else %}
              {% render_field field placeholder=field.label %}
              {% endif %}
              {% comment %} {{form|afl_validate_error:field}} {% endcomment %}
            
              {% endwith %}
              {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
              {% endfor %}
              {% else %}
              {% with field.field.widget.attrs.class|add:" form-control m-input is-valid" as field_class %}
              {% if field.field.widget.attrs.field_suffix %}
              <div class="input-group">
                {% render_field field class=field_class %}
                {% comment %} <div class="input-group-append">
                  {% afl_field_suffix form field %}
                </div> {% endcomment %}
              </div>
              {% elif field.field.widget.attrs.field_prefix %}
              <div class="input-group">
                {% comment %} <div class="input-group-prepend" style="width:100px;">
                  {% afl_field_prefix form field %}
                </div> {% endcomment %}
                {% render_field field class=field_class %}
            
              </div>
              {% else %}
              {% render_field field class=field_class %}
              {% endif %}
            
              {% endwith %}
              {% endif %}
              {% else %}
              {% with field.field.widget.attrs.class|add:" form-control m-input" as field_class %}
              {% if field.field.widget.attrs.field_suffix %}
              <div class="input-group">
                {% render_field field class=field_class %}
                {% comment %} <div class="input-group-append">
                  {% afl_field_suffix form field %}
                </div> {% endcomment %}
              </div>
              {% elif field.field.widget.attrs.field_prefix %}
              <div class="input-group">
                {% comment %} <div class="input-group-prepend" style="width:100px;">
                  {% afl_field_prefix form field %}
                </div> {% endcomment %}
                {% render_field field class=field_class %}
            
              </div>
            
              {% else %}
              {% render_field field class=field_class %}
              {% endif %}
              {% endwith %}
            
              {% endif %}
              {% if field.help_text %}
              <span class="m-form__help">{{ field.help_text }}</span>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          

          <div class="m-form__actions">
              <button class="btn btn-brand m-btn m-btn--custom m-btn--pill m-btn--wide m-btn--bolder m-btn--sm" id="add-staff">{% trans 'Create User' %}</button>
          </div>
                
       </form>
       {% else %}
          <div class="m-portlet m-portlet--mobile bg-transparent box-shadow-0">
               <div class="payout-earnings-wrapper" id="modify-wrapper">
                    <div class="payout-earnings-block">
                         <div class="row no-gutters">
                              {% trans 'Please wait until you become part of MLM.Your request is being processed.' %}
                         </div>
                    </div>
            </div>
          </div>  
       {% endif %}
      </div>

    </div>
  </div>
</div>
{% endblock %}
{% block javascript %}
  {{form_media.js}}

  <script type="text/javascript">
    var errorClass = 'invalid-feedback';
  </script>
  <script src="{% static 'frontend/js/jquery.validate.min.js' %}" type="text/javascript"></script>
  {% comment %} <script src="{% static 'afl_user/js/user-registration.js' %}" type="text/javascript"></script> {% endcomment %}
  <script src="{% static 'afl_custom_widget/js/password-toggle.js' %}" type="text/javascript"></script>
  <script type="text/javascript">
  //for preventing autocomplete form where autocomplete="off" not working such as in chrome browser
  $(document).ready(function() {
    var timer = window.setTimeout( function(){
        $('#id_password').prop('disabled',false);
        $('#id_confirmpswd').prop('disabled',false);
        clearTimeout(timer);
       },
       800);
  })
  </script>

  <script type="text/javascript">
  var loaderContainer = document.getElementById("loader");
  // Show loader
  function showLoader() {
    if (loaderContainer) {
      loaderContainer.style.display = "block";
    }
  }

  // Hide loader
  function hideLoader() {
    if (loaderContainer) {
      loaderContainer.style.display = "none";
    }
  }

  $.validator.addMethod(
    "regex",
    function(value, element, regexp) {
        var re = new RegExp(regexp);
        return this.optional(element) || re.test(value);
    },
    "Please check your input."
  );
  $.validator.addMethod(
    "regex1",
    function(value, element) {
      var re = /\d/; // At least one digit
      return this.optional(element) || re.test(value);
    },
    "Password must contain at least one digit."
  );
  $.validator.addMethod(
    "regex2",
    function(value, element) {
      var re = /[a-z]/; // At least one lowercase letter
      return this.optional(element) || re.test(value);
    },
    "Password must contain at least one lowercase letter."
  );
  $.validator.addMethod(
    "regex3",
    function(value, element) {
      var re = /[A-Z]/; // At least one uppercase letter
      return this.optional(element) || re.test(value);
    },
    "Password must contain at least one uppercase letter."
  );
  $.validator.addMethod(
    "regex4",
    function(value, element) {
      var re = /[~\!@#\$%\^&\*\(\)_\+{}":;'\[\]]/; // At least one special character
      return this.optional(element) || re.test(value);
    },
    "Password must contain at least one special character."
  );
  $.validator.addMethod(
    "passwordMatch",
    function(value, element) {
      var password1Valid = $(element).closest("form").find("#id_password").hasClass("valid");
      return password1Valid && value === $("#id_password").val()
    },
    ""
  );
  $.validator.addMethod(
    "passwordValid",
    function(value, element) {
      var password1Valid = $(element).closest("form").find("#id_password").hasClass("valid");
      return password1Valid
    },
    ""
  );
const specialCharacters = /[~\!@#\$%\^&\*\(\)_\+{}":;'\[\]]/;
const passwordRegex = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[~\!@#\$%\^&\*\(\)_\+{}":;'\[\]])/;
var rules = {
    "first_name": {
      regex: "^[a-zA-Z ]+$",
      maxlength :20,
    },
    "last_name": {
      regex: "^[a-zA-Z ]+$",
      maxlength :20,
    },
    email: {
      regex : /^(([^<>()\[\]#$|?/\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    },
    password: {
      minlength: 8,
      regex1 : true,
      regex2 : true,
      regex3 : true,
      regex4 : true,
    },
    confirmpswd: {
      passwordValid: true,
      passwordMatch: true,
    },
    phone_number: {
      required: true,
      number:true,
      minlength: 4,
      maxlength :12,
    },
    title: {
      required: true,
      minlength: 4,
      maxlength :120,
    },
};


var messages = {
    username: {
      regex: "Username can only be combination of underscore and alphanumeric characters. Underscore can't be used twice together (e.g. user__name1) and must be in between the alphanumeric combination. The number of characters must be between 5 to 15.",
    },
    "first_name": {
      regex: "First name must contain only alphabets."
    },
    "last_name": {
      regex: "Last name must contain only alphabets.",
    },
    password: {
      regex1: "Password must contain at least one digit.",
      regex2: "Password must contain at least one lowercase letter.",
      regex3: "Password must contain at least one uppercase letter.",
      regex4: "Password must contain at least one special character.",
    },
    confirmpswd: {
      passwordValid: " ",
      passwordMatch: "Confirmed password doesn't match.",
    },
};
  $("#register-form").validate({
    rules: rules,
    messages: messages,
    submitHandler: function(form) {
      swal({
          title: "{% trans 'Are you sure?' %}",
          text: `{% trans "You won't be able to revert this!" %}`,
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          cancelButtonText: "{% trans 'Cancel' %}",
          confirmButtonText: "{% trans 'Yes, Select It!' %}"
      }).then((result) => {
          if (result.value) {
            showLoader()
            var formData = new FormData(document.getElementById('register-form'));
            callApi({
              url: serverUrl + addStaffUrl,
              method: 'POST',
              data: formData,
              processData: false,
              contentType: false,
              success: function(response) {
                hideLoader();
                toastr.success("Staff created successfully!");
                setTimeout(function() {
                  window.location.reload();
                }, 500);
              },
              error: function(xhr, status, error) {
                hideLoader();
                if (xhr.status === 401 || xhr.status === 403) {
                  window.location.href = dashboardUrl
                } else if (xhr.status === 400) {
                  console.log(xhr, error)
                  setErrorMessage(xhr.responseJSON)
                } else {
                  toastr.error("Something went wrong please try again");
                }
              }
            });
          }
      });
    },
    invalidHandler: function(event, validator) {
        validator.showErrors();
    },

    onkeyup: false,

    onfocusout: function(element) {
        this.element(element);
    },
    errorPlacement: function(error, element) {
        if ($(element).attr('type') == 'checkbox'){
            element.parent().find('.invalid-feedback').remove()
            element.removeClass("is-valid");
            element.addClass("is-invalid");
        } else {
            element.parent().find('.invalid-feedback').remove()
            errorDiv = $('<div class="invalid-feedback"></div>');
            errorDiv.append(error.text());
            if(element.hasClass("select2-hidden-accessible")){
                element.parents('.form-group').append(errorDiv);
            }else{
                element.after(errorDiv);
            }
            element.removeClass("is-valid");
            element.addClass("is-invalid");
        }
    },
    success: function(error, element) {
        $(element).parent().find(errorClass).remove()
        $(element).removeClass("is-invalid");
        if ($(element).attr('name') != 'security_token') {
            if ($(element).val()){
                $(element).addClass("is-valid");
            }
        }
    }

});
  </script>

{% endblock %}


{% block stylesheet %}
  {{form.media.css}}
  <style type ="text/css">
  
    .password-field{
      top:30px ;
    }
    .loader{
      position: absolute;
      left: 0px;
      top: 0px;
      width: 100%;
      height: 100%;
      opacity: 70%;
      z-index: 9999;
      background: url("{% static 'afl_user/img/loader.gif' %}") 50% 50% no-repeat rgb(249,249,249);
    }
  </style>
{% endblock stylesheet %}