compilent_mngmt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('account.urls')),
    path('', include('frontend.urls')),
    path('api/v1/core/', include('core.urls'))
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (EmployeeList, EmployeeRetrieveView, EmployeeUpdateView, compilent_registration, CompilentList, CompilentRetrieveView,
                    CompilentUpdateView, CompilentWorkflowUpdateView, GetSource)

urlpatterns = [
    path('employee/list/', EmployeeList.as_view(), name='employee_list'),
    path('employee/details/<id>/', EmployeeRetrieveView.as_view(), name='employee_details'),
    path('employee/details/<id>/update/', EmployeeUpdateView.as_view(), name='employee_update'),
    path('add-complaint/', compilent_registration, name='compilent_registration'),
    path('complaint/list/', CompilentList.as_view(), name='compilent_list'),
    path('complaint/details/<id>/', CompilentRetrieveView.as_view(), name='compilent_details'),
    path('complaint/details/<id>/update/', CompilentUpdateView.as_view(), name='compilent_update'),
    path('complaint/details/<id>/workflow/', CompilentWorkflowUpdateView.as_view(), name='compilent_update'),
    path('complaint/source/', GetSource.as_view(), name='api_order_get_source'),
]

frontend/urls.py
from django.urls import path
from .views import (Home, UserLoginView, AflDasboardView, ManageStaff, AddNewEmployee, AflManageMemberEdit, ManageComplaint,
                    AddNewComplaint, AflManageComplaintsEdit, ComplaintView, AflManageComplaintsWorkflow)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', UserLoginView.as_view(), name='login_url'),
    path('dashboard/', AflDasboardView.as_view(), name='dashboard'),
    path('manage-staff/', ManageStaff.as_view(), name='manage_staff'),
    path('add-new-employee/', AddNewEmployee.as_view(), name='add_employee'),
    path('manage-employee/edit/', AflManageMemberEdit.as_view(), name="manage_members-edit"),
    path('manage-complaint/', ManageComplaint.as_view(), name='manage_complaint'),
    path('add-new-complaint/', AddNewComplaint.as_view(), name='add_complaint'),
    path('manage-complaint/edit/', AflManageComplaintsEdit.as_view(), name="manage_complaint-edit"),
    path('complaints/view/', ComplaintView.as_view(), name="complaint_view"),
    path('manage-complaint/workflow/', AflManageComplaintsWorkflow.as_view(), name="manage_complaint-workflow"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.conf import settings

class UserLoginForm(forms.Form):
	email = forms.CharField(label=_('Email'),max_length=250,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Email'}))
	password = forms.CharField(label=_('Password'),max_length=250,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Password'}))
	def __init__(self, *args, **kwargs):
		self.request = None
		if 'request' in kwargs:
			self.request = kwargs.pop('request', None)
		kwargs.setdefault('label_suffix', '')
		super(UserLoginForm, self).__init__(*args, **kwargs)

class AflAbstractUserForm(forms.Form):
	first_name = forms.CharField(max_length=20,label=_('First Name'))
	last_name = forms.CharField(max_length=20, label=_('Last Name'))
	email = forms.CharField(max_length=50, label=_('Email'))
	phone_number = forms.CharField(max_length=10, label=_('Phone Number'))
	title = forms.CharField(max_length=120, label=_('Title'))

	def __init__(self, *args, **kwargs):
		# pp("AflAbstractUserForm---------------")
		# Get 'initial' argument if any	
		initial_arguments = kwargs.get('initial', None)
		if not hasattr(self,'request') or not self.request:
			if initial_arguments:
				self.request = initial_arguments.get('request',None)
			else:
				self.request = None

		super(AflAbstractUserForm, self).__init__(*args, **kwargs)
		self.fields['last_name'].label = _('Last Name')
		self.fields['email'].label = _('Email address')
		self.fields['phone_number'].label = _('Phone Number')
		self.fields['title'].label = _('Title')

class UserCreationForm(AflAbstractUserForm):
	"""A form for creating new users. Includes all the required
	fields, plus a repeated password."""
	password = forms.CharField(label=_('Password'), widget=forms.TextInput(attrs={'class':'form-control','placeholder':_('Password')}))
	confirmpswd = forms.CharField(label=_('Password confirmation'), widget=forms.TextInput(attrs={'class':'form-control','placeholder':_('Password')}))
 
class AddNewEmployeeForm(UserCreationForm):
	"""docstring for AddNewStaffForm"""

	def __init__(self, *args, **kwargs):
		super(AddNewEmployeeForm, self).__init__(*args, **kwargs)


		if 'password' in self.fields:
			self.fields['password'].widget.attrs.update({
				'autocomplete': 'off',
				'disabled':True          #for preventing autocomplete some browser where above line not working such as Chrome
			})
		if 'confirmpswd' in self.fields:
			self.fields['confirmpswd'].widget.attrs.update({
				'autocomplete': 'off',
				'disabled':True			#for preventing autocomplete some browser where above line not working such as Chrome
			})
		self.fields['password'].label = _("Password")
		self.fields['confirmpswd'].label = _("Password confirmation")

class UserProfileForm(AflAbstractUserForm):

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop('request', None)
		super().__init__(*args, **kwargs)

class AddNewCompliantForm(forms.Form):
	options = (
		('', _('Please select')),
	)
	title = forms.CharField(label=_("Title"), required=True)
	description = forms.CharField(label=_("Description"), required=True, widget=forms.Textarea(attrs={'rows': 4, 'cols': 25}))
	assignee = forms.ChoiceField(
        choices=[
            ('', _('Please select'))
        ],
        label=_("Assignee"),
        widget=forms.Select(attrs={
            'class': 'form-control',
            'data-placeholder': _('Choose assignee'),
            'data-url': f'{settings.SERVER_URL}/api/v1/assignee-autocomplete/'
        })
    	)

	def __init__(self, *args, **kwargs):
		self.request = None
		if 'request' in kwargs:
			self.request = kwargs.pop('request', None)
		super(AddNewCompliantForm, self).__init__(*args, **kwargs)
		instance = kwargs.get('instance',{})

class EditComplaintForm(forms.Form):
	options = (
		('', _('Please select')),
	)
	title = forms.CharField(label=_("Title"), required=True)
	description = forms.CharField(label=_("Description"), required=True, widget=forms.Textarea(attrs={'rows': 4, 'cols': 25}))
	assignee = forms.ChoiceField(
        choices=[
            ('', _('Please select'))
        ],
        label=_("Assignee"),
        widget=forms.Select(attrs={
            'class': 'form-control',
            'data-placeholder': _('Choose assignee'),
            'data-url': f'{settings.SERVER_URL}/api/v1/assignee-autocomplete/'
        })
    	)

	def __init__(self, *args, **kwargs):
		self.request = None
		if 'request' in kwargs:
			self.request = kwargs.pop('request', None)
		super(EditComplaintForm, self).__init__(*args, **kwargs)
		instance = kwargs.get('instance',{})

class WorkflowComplaintForm(forms.Form):
	STATUS_CHOICES=[
		('new','New'),
		('triaged','Triaged'),
		('in_progress','In progress'),
		('resolved','Resolved'),
		('closed','Closed')
	]
	status = forms.ChoiceField(choices=STATUS_CHOICES, label=_('Status'), widget=forms.Select(), required=True)
	status_remark = forms.CharField(label=_("Remark"), required=True, widget=forms.Textarea(attrs={'rows': 4, 'cols': 25}))

	def __init__(self, *args, **kwargs):
		self.request = None
		if 'request' in kwargs:
			self.request = kwargs.pop('request', None)
		super(WorkflowComplaintForm, self).__init__(*args, **kwargs)
		instance = kwargs.get('instance',{})

frontend/templates/frontend/compliant/add-new-complaint.html
{% extends "frontend/new_base.html" %}
{% load static %}
{% load i18n %}
{% load templatehelpers %}
{% load widget_tweaks %}

{% block stylesheet %}
<style type="text/css">
  .loader{
    position: absolute;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    opacity: 70%;
    z-index: 9999;
    background: url("{% static 'afl_user/img/loader.gif' %}") 50% 50% no-repeat rgb(249,249,249);
  }
  select {
    appearance: auto !important;
    background-color: white !important;
  }
</style>
{% endblock %}

{% block content %}
<div class="m-content">
   <div class="loader" id="loader" style="display:none"></div>
    <div class="m-portlet-center">
            <div class="m-portlet m-portlet--full-height">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <span class="m-portlet__head-icon">
                <i class="flaticon-user m--font-primary"></i>
              </span>
                            <h3 class="m-portlet__head-text">
                              {% trans 'Add New Compilent' %}
                            </h3>
                        </div>
                    </div>
                </div>
                <form id="token-form" method="{{form.method|default:'POST'}}" class="{{form.class}} m-form" action="{{form.action|default:request.path}}" {% if files %} enctype="multipart/form-data" {% endif %}>


                  <!-- ------------- -->
                  <div class="m-portlet__body">
                    {% if not token_included %}
                    {% csrf_token %}
                    {% endif %}

                    <div class="container-fluid">
                      {% if form.non_field_errors %}
                      <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                        {{ error }}
                        {% endfor %}
                      </div>
                      {% endif %}

                      {% for hidden_field in form.hidden_fields %}
                      {% comment %}
                      {% if hidden_field.errors %}
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        {% for error in hidden_field.errors %}
                        {{ error }}
                        {% endfor %}

                      </div>
                      {% endif %}
                      {% endcomment %}
                      {{hidden_field}}
                      {% endfor %}
                    </div>
                    <div class="row">
                    {% for field in form.visible_fields %}
                    
                    {% if field.name != 'phone_number' and field.name != 'phone_code' %}
                    <div class="col-md-6">
                    <div class="form-group">
                      {% if field.field.widget.is_toggle %}
                      {% render_field field placeholder=field.label %}
                      {% elif field.field.widget.input_type == 'checkbox' and field.field.widget.attrs.key != 'default_offer_checkbox_toggle' and field.field.widget.attrs.key != 'status_checkbox_toggle' %}

                      <label class="m-checkbox m-checkbox--solid">
                        {% I18n_advanced_label_tag field %}
                        {% render_field field placeholder=field.label %}
                        <span></span>
                      </label>
                      {% elif field.field.widget.attrs.placeholder %}   
                        {% I18n_advanced_label_tag field %}
                        <div>
                          <div id="prefix-{{field.name}}" class="{{field_prefix_class}}">{{prefix_content}}</div>
                          {% if extra %}
                          {% comment %} {{ extra|getattribute:field.name|safe }} {% endcomment %}
                          {% endif %}
                        </div>
                        <div class="pt-2">
                          {% render_field field placeholder=field.field.widget.attrs.placeholder %}
                          <div id="suffix-{{field.name}}" class="{{field_suffix_class}}">{{suffix_content}}</div>
                        </div> 
                      
                      {% else %}   
                      {% I18n_advanced_label_tag field %}
                      {% comment %} {{form|afl_validate_help_text:field}}  {% endcomment %}
                      <div>
                        <div id="prefix-{{field.name}}" class="{{field_prefix_class}}">{{prefix_content}}</div>
                        {% if extra %}
                        {% comment %} {{ extra|getattribute:field.name|safe }} {% endcomment %}
                        {% endif %}
                      </div>
                      <div class="pt-2 5">
                        {% render_field field placeholder=field.label %}
                        {% comment %} {{form|afl_validate_error:field}} {% endcomment %}
                        <div id="suffix-{{field.name}}" class="{{field_suffix_class}}">{{suffix_content}}</div>
                      </div>
                      {% endif %}
                      {% if field.help_text %}
                      {% comment %} <small class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small> {% endcomment %}
                      {% endif %}
                    </div>
                  </div>
                    {% elif field.name == 'phone_number' %}
                    <div class="col-md-6">
                    <div class="form-group">
                      <label class="required ">
                      {% if form.phone_number and form.phone_code %}
                      {{field.label}}{% if field.field.required %} *{% endif %}:
                      </label>
                      <div class="input-group mt-2">
                       <div class="input-group-prepend" style="width:100px;">
                         {% if form.phone_code %}
                         {% with field=form.phone_code %}
                         {% render_field field placeholder=field.label %}
                         {% comment %} {{form|afl_validate_error:field}} {% endcomment %}
                         {% endwith %}
                         {% endif %}
                       </div>
                       {% if form.phone_number %}
                       {% with field=form.phone_number %}
                       {% render_field field placeholder=field.label %}
                       {% comment %} {{form|afl_validate_error:field}} {% endcomment %}
                       {% comment %} {{form|afl_validate_help_text:field}} {% endcomment %}
                       {% endwith %}
                       {% endif %}
                     </div>
                     {% endif %}
                   </div>  
                  </div>
                   {% endif %}
                
                   {% endfor %}
                  </div>
                 </div>
                 <!-- ------------- -->
                 <div class="m-portlet__foot m-portlet__foot--fit">
                  <div class="m-form__actions">
                    <div class="row">
                      <div class="col-lg-9 m-3">
                        {% if form.buttons %} {% if form.token_field.errors or not form.token_field.value %}

                        <div id="buttons-parent" class="buttons">
                          <div class="m-loader m-loader--brand custom-loader" style="width: 30px; display: none;"></div>
                          <button type="submit" name="token_submit"  id="token-send" class=" btn btn-brand">
                            {% trans 'Save changes'%}
                          </button>
                          <button type="reset" id="form-reset" class=" btn btn-warning">
                            {% trans 'Clear'%}
                          </button>
                          <button type="button" name="back" onclick="window.history.back();" id="form-back" class=" btn btn-outline-dark">
                            {% trans 'Back'%}
                          </button>
                        </div>

                        {% else %} {% include 'buttons.html' with buttons=form.buttons %} {% endif %} {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
                </form>
            </div>
    </div>
</div>
{% endblock %}



{% block javascript %}
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script type="text/javascript" src="{% static 'autocomplete_light/jquery.init.js' %}"></script>
  <script type="text/javascript" src="{% static 'autocomplete_light/dal-custom/autocomplete.init.js' %}"></script>
  <script type="text/javascript" src="{% static 'autocomplete_light/forward.js' %}"></script>
  <script type="text/javascript" src="{% static 'autocomplete_light/select2.js' %}"></script>
  <script type="text/javascript" src="{% static 'autocomplete_light/jquery.post-setup.js' %}"></script>
  {% if page_filter %}
    {% include 'filter/filter.js' with page_filter=page_filter %}
  {% endif %}

  <script>
  var manage_complaint_url = "{{ manage_complaint }}"

  var d = new Date();
  var maxDate = new Date(d.getFullYear(), d.getMonth(), d.getDate());

$(document).ready(function(){

    $.validator.addMethod(
      "regex",
      function(value, element, regexp) {
          var re = new RegExp(regexp);
          return this.optional(element) || re.test(value);
      },
      "Please check your input."
    );
    var errorClass = 'invalid-feedback';
    var rules = {
      assignee: {
        required: true
      },
      title: {
        required: true,
        minlength: 4,
        maxlength :120,
      },
      description: {
        required: true,
        minlength: 4,
        maxlength :250,
      },
    }
    var messages = {
      assignee: {
        required: "Please select an assignee."
      }
    }
    $('#token-form').validate({
      rules:rules,
      messages:messages,
      submitHandler:(form) => {
        event.preventDefault();
        token_send();
      },
      invalidHandler: (event, validator) => {
          validator.showErrors();
      },
      onkeyup: false,
      onfocusout:function(element){
          this.element(element);
      },
      errorPlacement:(error, element) => {
        element.parent().find('.invalid-feedback').remove();
        if (element.is('select')) {
            error.insertAfter(element.next('.select2'));
            error.css('margin-top', '22px');
        } else {
            error.insertAfter(element);
        }
        element.removeClass("is-valid").addClass("is-invalid");
      },
      success:(label,element) => {
          $(element).parent().find(errorClass).remove()
          $(element).removeClass("is-invalid");
          $(element).addClass("is-valid");
      }
    });

    var loaderContainer = document.getElementById("loader");
    // Show loader
    function showLoader() {
      if (loaderContainer) {
        loaderContainer.style.display = "block";
      }
    }

    // Hide loader
    function hideLoader() {
      if (loaderContainer) {
        loaderContainer.style.display = "none";
      }
    }

    function token_send(obj){
      showLoader()
      var formData = new FormData(document.getElementById('token-form'));
      callApi({
        url: serverUrl + addCompliantUrl,
        method: 'POST',
        data: formData,
        processData: false,
        contentType: false,
        success: function(response) {
          hideLoader();
          toastr.success("Appointment created successfully!");
          setTimeout(function() {
            window.location.href = manage_complaint_url;
          }, 500);
        },
        error: function(xhr, status, error) {
          hideLoader();
          if (xhr.status === 401 || xhr.status === 403) {
            window.location.href = dashboardUrl
          } else if (xhr.status === 400) {
            console.log(xhr, error)
            setErrorMessage(xhr.responseJSON)
          } else {
            toastr.error("Something went wrong please try again");
          }
        }
      });
    }

    let $assigneeSelect = $('#id_assignee');

    // Initialize Select2
    $assigneeSelect.select2({
      placeholder: $assigneeSelect.attr('data-placeholder'),
      minimumInputLength: 1,
      language: {
        inputTooShort: function(args) {
          return "Please enter 1 or more characters";
        }
      },
      ajax: {
        url: $assigneeSelect.attr('data-url'),
        dataType: 'json',
        delay: 250,
        processResults: function (data) {
          return {
            results: data.results.map(function(item) {
              return { id: item.id, text: item.text };
            })
          };
        }
      }
    });

  })
</script>
{% endblock %}

frontend/templates/frontend/compliant/complaint-view.html
{% extends "frontend/new_base.html" %}
{% load i18n %}
{% load templatehelpers %}
{% load static %}


{% block maintitle %} {{label}} {% endblock %}

{% block content %}
<div class="m-content" id="m-view-order">
  <div class="loader" id="loader" style="display:none"></div>
  <div class="d-flex justify-content-end">

  </div>
  <div class="m-portlet m-portlet--height-fluid ">
    <div class="m-portlet__head" data-toggle="collapse" data-target="#general-info" aria-expanded="true" aria-controls="general-info">
      <div class="m-portlet__head-caption">
        <div class="m-portlet__head-title">
          <span class="m-portlet__head-icon">
            <i class="la la-info text-primary"></i>
          </span>
          <h3 class="m-portlet__head-text">{% trans 'General Information' %}</h3>
        </div>
      </div>
      <div class="m-portlet__head-tools">
        {% comment %} <a id="EditAppointmentOption" href="{% abs_url 'manage_appointment-edit' request %}?appointment_id={{appointment_id}}&role=appointment&redirect=true&from=manage_appointments" target="_blank" class="btn btn-inverse-warning px-4 py-2 btn-crd-hed bulk-action-button m-3"><i class="bi bi-pencil mr-1"></i>{% trans ' Edit' %}</a> {% endcomment %}
        {% comment %} <a id="SendSmsOption" style="display: none" href="{% url 'order_form_url' %}?order_id={{orderid}}" target="_blank" class="btn btn-inverse-warning px-4 py-2 btn-crd-hed bulk-action-button m-3"><i class="bi bi-telephone mr-1"></i> Resend SMS</a> {% endcomment %}
        <div class="collapse-icon"><i class="la la-angle-down"></i></div>
      </div>
    </div>
    <div id="general-info" class="collapse show" data-parent="#m-view-order">
      <div class="row m-portlet__body">
        {% for field in general_fields %}
          {% if not forloop.counter == 1 %}
          <div class="col-md-6">
          {% else %}
            <div class="col-md-6">
          {% endif %}
            <div class="bonus-det p-3" id={{field.key}}>
              <div class="label-div-{{field.key}}">
                <h6 class="h6-div-{{field.key}}">{% trans field.text %}</h6>
              </div>
              <div class="value-div-{{field.key}}">
                -
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>


{% endblock %}

{% block stylesheet %}
<style type ="text/css">
  .loader{
    position: absolute;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    opacity: 70%;
    z-index: 9999;
    background: url("{% static 'afl_user/img/loader.gif' %}") 50% 50% no-repeat rgb(249,249,249);
  }
</style>
{% endblock stylesheet %}

{% block javascript %}
<script type="text/javascript">
var previous = "{{ previous }}";
var compliant_id = {{ compliant_id }};
var general_fields = {{ general_fields|safe }};
window.onload = function() {
  isUserEditPermission = false;
  showLoader();
  // callApi({
	// 	url: serverUrl + checkPermissionUrl,
	// 	method: 'POST',
	// 	contentType: 'application/json',
	// 	data: JSON.stringify({'codenames': ['apis.add_afluser']}),
	// 	success: function(response) {
	// 		if (response.status_code === 200) {
	// 			var respData = response.data;
	// 			for (var key in respData) {
	// 				if (respData.hasOwnProperty(key)) {
	// 					isUserEditPermission = respData[key]
	// 				}
	// 			}
  //       if (isUserEditPermission) {
  //         if (document.getElementById('EditOrderOption')) {
  //           if (previous === 'incomplete_orders' || previous === 'complete_orders') {
  //             document.getElementById('EditOrderOption').style.display = 'block';
  //           }
  //         }
  //       } else {
  //         if (previous === 'incomplete_orders') {
  //           document.getElementById('EditOrderOption').style.display = 'block';
  //         }
  //       }
  //       callApi({
  //         url: serverUrl + getContactFormUrl,
  //         method: 'GET',
  //         params: {order_id: orderid},
  //         success: function(response) {
  //           if (response.status_code === 200) {
  //             var orderData = response.data;
  //             setDetails(orderData);
  //             hideLoader();
  //           }
  //         },
  //         error: function(xhr, status, error) {
  //           hideLoader();
  //           if (xhr.status === 401 || xhr.status === 403) {
  //             window.location.href = dashboardUrl
  //           } else {
  //             toastr.error(Trans.trans("Something went wrong please try again"));
  //           }
  //         }
  //       });
  //     }
  //   }
  // });
  getComplaintUrl = getComplaintUrl.replace('<complaint_id>', compliant_id);
  callApi({
    url: serverUrl + getComplaintUrl,
    method: 'GET',
    success: function(response) {
        var complaintData = response;
        setDetails(complaintData);
        hideLoader();
    },
    error: function(xhr, status, error) {
      hideLoader();
      if (xhr.status === 401 || xhr.status === 403) {
        window.location.href = dashboardUrl
      } else {
        toastr.error("Something went wrong please try again");
      }
    }
  });
};

function setDetails(orderData) {
  if (orderData.hasOwnProperty('pk')) {
    for (var i = 0; i < general_fields.length; i++) {
      field = general_fields[i];
      if (field.key) {
        var keys = field.key.split('-');
        var nestedValue = orderData;
        for (var j = 0; j < keys.length; j++) {
          nestedValue = nestedValue[keys[j]];
          if (nestedValue === undefined) {
            break;
          }
        }
        var element = document.querySelector(`.value-div-${field.key}`);
        if (element) {
            element.innerHTML = nestedValue ? nestedValue : '-';
        }
      }
    }
  }
}

var loaderContainer = document.getElementById("loader");
// Show loader
function showLoader() {
	if (loaderContainer) {
		loaderContainer.style.display = "block";
	}
}

// Hide loader
function hideLoader() {
	if (loaderContainer) {
		loaderContainer.style.display = "none";
	}
}

</script>
{% endblock %}